module-1 task-1
js-tasks-ru/vue-20220809_forauto77 pull request #1
Opened 2022-08-15 08:49 UTC by roman162

2022-08-15 08:49 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @ShGKme должен запустить тесты.

2022-08-15 11:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-15 11:49 UTC, ShGKme reviewed
Все решённые задачи приняты, но решены не все добавленные задачи.

`package-lock` файл важен. Он используется для воспроизводимой установки зависимостей. Это защищает от проблем, когда маленькое обновление библиотек ломает работу приложения, а также ускоряет установку зависимостей

2022-08-15 13:38 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-08-16 12:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-08-16 12:26 UTC, ShGKme requested changes
В `01-basics/03-MarkedList` требуется воспользоваться привязкой классов через объект, чтобы лишний раз попрактиковаться с ним во Vue. Он часто используется.

В остальном всё хорошо.

2022-08-16 12:26 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  }
Кажется, все эти методы не используются...

2022-08-16 12:26 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +        <label><input type="radio" v-model="meetupId" name="meetupId" value="5" /> 5</label>
Можно использовать `v-for`, чтобы избежать повторений.

2022-08-16 12:26 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  }
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства обычно называют, как свойства, а не как функции (не с глагола, без get).

2022-08-16 12:26 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          </li>
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - булево значение, которое обозначает, что класс требуется добавить.

[https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings](https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings)

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы.

2022-08-16 13:05 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-08-16 13:43 UTC, ShGKme approved these changes
Все задачи приняты.

Но `package-lock` файл лучше вернуть.

2022-08-16 13:43 UTC, merged